apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gpt-oss-20b-predictor
  namespace: lightspeed-llm
spec:
  to:
    kind: Service
    name: gpt-oss-20b-predictor
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
