apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # oc kustomize https://github.com/redhat-na-ssa/ocp-web-terminal-enhanced/bootstrap > dump.yaml
  - operator.yaml
  - web-terminal-tooling.yaml
